name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: denolib/setup-deno@master

      - name: Print deno version
        run: deno --version

      - name: Check format
        run: deno fmt

      - name: Run tests
        run: make ci
